name: Generate files.json
on:
  push:
    paths:
      - 'files/**'
      - 'tools/generate_files_json.js'
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install (none required)
        run: echo "No deps"
      - name: Run generator
        run: node tools/generate_files_json.js
      - name: Commit files.json
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add files/files.json || true
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "chore: regenerate files.json"
            git push
          fi
